extends Node

var failures: Array[String] = []

func _ready() -> void:
	call_deferred("_run")

func _run() -> void:
	var graph := NetworkGraph.new()
	var sphere := SphereDefinition.new(&"test_sphere", "Test Sphere", [], &"")
	_check(graph.add_sphere(sphere), "sphere added")
	var start := NetworkNodeDefinition.new(&"start", "Start", NetworkNodeDefinition.NodeType.GATEWAY)
	start.sphere_id = sphere.id
	var sealed := NetworkNodeDefinition.new(&"sealed", "Sealed", NetworkNodeDefinition.NodeType.FILE_SERVER)
	sealed.sphere_id = sphere.id
	_check(graph.add_node(start) and graph.add_node(sealed), "nodes added")
	_check(graph.add_link(NetworkLinkDefinition.new(&"sealed_path", start.id, sealed.id, false, false, true)), "locked path added")
	var position := PlayerNetworkPosition.new(start.id, 0)
	Game.network_graph = graph
	Game.player_network_position = position
	Game.ice_controller = IceController.new(graph, position, PlayerKnowledge.new())
	var host_definition := IceDefinition.new(&"AUTHOR_HOST_GUARD", "Host Guard", 2, 999999, 1, [], 8, 2); host_definition.binding_mode = IceDefinition.BindingMode.HOST_BOUND
	var mobile_definition := IceDefinition.new(&"AUTHOR_PATROL", "Patrol", 2, 2, 1, [start.id, sealed.id], 8, 1)
	Game.ice_controller.add_ice(IceInstance.new(&"HOST_TEMPLATE", host_definition, start.id))
	Game.ice_controller.add_ice(IceInstance.new(&"MOBILE_TEMPLATE", mobile_definition, start.id))
	var controller := NetworkAuthoringController.new()
	get_tree().root.add_child(controller)
	controller.configure(null)
	_check(controller.set_mode(NetworkAuthoringState.Mode.AUTHOR_GOD), "debug build enters author god")
	_check(controller.is_god_mode(), "god mode active")
	_check(bool(controller.move_author_to_node(sealed.id).success), "god relocation ignores locked path and traversal points")
	_check(position.current_node_id == sealed.id and position.traversal_points == 0, "relocation changes position without gameplay cost")
	var graph_identity := graph.get_instance_id()
	_check(controller.set_mode(NetworkAuthoringState.Mode.AUTHOR_TEST), "switches to author test")
	_check(Game.network_graph.get_instance_id() == graph_identity, "god/test toggle does not reload graph")
	_check(not controller.is_god_mode(), "test mode restores player rules")
	_check(not bool(controller.move_author_to_node(start.id).success), "test mode rejects god relocation")
	controller.set_mode(NetworkAuthoringState.Mode.AUTHOR_GOD)
	controller.select_object(NetworkSelectionState.Kind.NODE, start.id)
	var service_result := controller.add_service(NodeServiceCatalog.DATABASE)
	var service_id := StringName(service_result.get("service_id", &""))
	_check(bool(service_result.success) and graph.get_node(start.id).get_services_by_type(NodeServiceCatalog.DATABASE).size() == 1, "registered service type can be added")
	controller.select_object(NetworkSelectionState.Kind.SERVICE, service_id)
	_check(bool(controller.configure_selected_service({"display_name": "Records", "service_type": NodeServiceCatalog.FILESYSTEM, "security_level": 4}).success) and controller._selected_service().security_level == 4, "service public properties configure")
	var remove_service_result := controller.remove_selected_service()
	var remove_service_command := controller.command_history.back() as NetworkAuthorCommand
	_check(bool(remove_service_result.success) and controller._service_owner(service_id) == null and bool(remove_service_command.undo().success), "service remove command undoes")
	controller.select_object(NetworkSelectionState.Kind.NODE, start.id)
	var stationary_result := controller.add_stationary_ice(host_definition.id)
	var stationary_id := StringName(stationary_result.get("ice_id", &""))
	_check(bool(stationary_result.success) and Game.ice_controller.get_ice(stationary_id).definition.is_host_bound(), "stationary ICE uses host-bound runtime representation")
	controller.select_object(NetworkSelectionState.Kind.ICE, stationary_id)
	_check(bool(controller.configure_selected_ice({"operational": false, "state": IceState.Value.DORMANT, "detection_capability": 3}).success) and not Game.ice_controller.get_ice(stationary_id).operational, "ICE enable state and public properties configure")
	var remove_ice_result := controller.remove_selected_ice()
	var remove_ice_command := controller.command_history.back() as NetworkAuthorCommand
	_check(bool(remove_ice_result.success) and Game.ice_controller.get_ice(stationary_id) == null and bool(remove_ice_command.undo().success), "ICE remove command undoes")
	controller.select_object(NetworkSelectionState.Kind.SPHERE, sphere.id)
	var mobile_result := controller.add_mobile_ice(mobile_definition.id, sealed.id)
	var authored_mobile := Game.ice_controller.get_ice(StringName(mobile_result.ice_id))
	_check(bool(mobile_result.success) and authored_mobile.current_node_id == sealed.id and authored_mobile.sphere_id == sphere.id, "mobile ICE belongs to selected sphere and starts within it")
	controller.select_object(NetworkSelectionState.Kind.ICE, authored_mobile.instance_id)
	_check(not bool(controller.configure_selected_ice({"patrol_route": [&"OUTSIDE_BOUNDARY"]}).success), "mobile ICE patrol is constrained to its boundary")
	authored_mobile.alert_level = 37
	var mobile_identity := authored_mobile.get_instance_id()
	controller.set_mode(NetworkAuthoringState.Mode.AUTHOR_TEST)
	_check(not Game._debug_author_god_mode and Game.ice_controller.get_ice(authored_mobile.instance_id).get_instance_id() != mobile_identity, "author test uses a clean temporary runtime")
	controller.set_mode(NetworkAuthoringState.Mode.AUTHOR_GOD)
	_check(Game._debug_author_god_mode and Game.ice_controller.get_ice(authored_mobile.instance_id).alert_level == 37, "returning to god discards test consequences and restores authored ICE state")
	controller.select_object(NetworkSelectionState.Kind.NODE, start.id)
	var add_result := controller.add_connected_node()
	var authored_node_id := StringName(add_result.get("node_id", &""))
	var authored_path_id := StringName(add_result.get("path_id", &""))
	_check(bool(add_result.get("success", false)) and graph.get_node(authored_node_id) != null and graph.get_link(authored_path_id) != null, "add connected node creates node and path")
	_check(controller.selection.object_id == authored_node_id, "new node is selected")
	var duplicate_result := controller.duplicate_selected_node()
	var duplicate_id := controller.selection.object_id
	_check(bool(duplicate_result.success) and graph.get_node(duplicate_id) != null and duplicate_id != authored_node_id, "duplicate node creates a stable independent node")
	_check(controller.is_dirty(), "authoring mutations set the unsaved indicator state")
	_check(bool(controller.undo().success) and graph.get_node(duplicate_id) == null, "Ctrl+Z command path undoes the latest mutation")
	_check(bool(controller.redo().success) and graph.get_node(duplicate_id) != null, "Ctrl+Shift+Z command path redoes the mutation")
	controller.select_nodes([authored_node_id, duplicate_id])
	_check(controller.selection.node_ids.size() == 2 and controller._selection_breadcrumbs().contains("2 nodes selected"), "multi-select tracks nodes and reports breadcrumbs")
	_check(bool(controller.delete_selection().success) and graph.get_node(authored_node_id) == null and graph.get_node(duplicate_id) == null, "delete selection removes multiple nodes as one command")
	_check(bool(controller.undo().success) and graph.get_node(authored_node_id) != null and graph.get_node(duplicate_id) != null, "multi-node deletion undoes atomically")
	controller.select_object(NetworkSelectionState.Kind.NODE, authored_node_id)
	_check(bool(controller.set_selected_node_type(NetworkNodeDefinition.NodeType.SYSTEM).success) and graph.get_node(authored_node_id).node_type == NetworkNodeDefinition.NodeType.SYSTEM, "node type uses gameplay enum")
	controller.select_object(NetworkSelectionState.Kind.PATH, authored_path_id)
	_check(bool(controller.set_selected_path_locked(true).success) and graph.get_link(authored_path_id).locked, "path locks through command")
	_check(bool(controller.set_selected_path_locked(false).success) and not graph.get_link(authored_path_id).locked, "path unlocks through command")
	controller.select_object(NetworkSelectionState.Kind.NODE, authored_node_id)
	var delete_result := controller.delete_selected_node()
	_check(bool(delete_result.get("success", false)) and graph.get_node(authored_node_id) == null and graph.get_link(authored_path_id) == null, "node deletion removes incident paths and sphere membership")
	var delete_command := controller.command_history.back() as NetworkAuthorCommand
	_check(bool(delete_command.undo().success) and graph.get_node(authored_node_id) != null and graph.get_link(authored_path_id) != null, "delete-node command retains undo state")
	controller.select_object(NetworkSelectionState.Kind.PATH, authored_path_id)
	var delete_path_result := controller.delete_selected_path()
	var delete_path_command := controller.command_history.back() as NetworkAuthorCommand
	_check(bool(delete_path_result.success) and graph.get_link(authored_path_id) == null and bool(delete_path_command.undo().success), "delete-path command executes and undoes")
	var extra_link := NetworkLinkDefinition.new(&"AUTHOR_TEST_PATH", start.id, authored_node_id)
	var add_path_command := AddPathCommand.new(controller._command_context(), extra_link)
	_check(bool(add_path_command.execute().success) and graph.get_link(extra_link.id) != null and bool(add_path_command.undo().success), "add-path command executes and undoes")
	controller.select_object(NetworkSelectionState.Kind.NODE, sealed.id)
	_check(not bool(controller.delete_selected_node().success), "current node deletion is refused")
	controller.select_object(NetworkSelectionState.Kind.SPHERE, sphere.id)
	_check(controller._inspection_text().contains("Test Sphere") and controller._inspection_text().contains("sealed"), "sphere inspector lists members")
	controller.select_object(NetworkSelectionState.Kind.NODE, start.id)
	var create_sphere_result := controller.create_sphere()
	var authored_sphere_id := StringName(create_sphere_result.get("sphere_id", &""))
	var authored_sleeve_id := StringName(create_sphere_result.get("sleeve_id", &""))
	_check(bool(create_sphere_result.success) and graph.get_node(start.id).sphere_id == authored_sphere_id and graph.get_security_sleeve(authored_sleeve_id) != null, "sphere creation includes selected node and real sleeve")
	controller.select_object(NetworkSelectionState.Kind.NODE, sealed.id)
	_check(bool(controller.add_selected_node_to_sphere(authored_sphere_id).success) and graph.get_node(sealed.id).sphere_id == authored_sphere_id, "single-membership node moves into sphere")
	_check(bool(controller.remove_selected_node_from_sphere().success) and graph.get_node(sealed.id).sphere_id == NetworkGraph.LEGACY_UNASSIGNED_SPHERE_ID, "remove membership moves node to unassigned sphere")
	controller.select_object(NetworkSelectionState.Kind.NODE, start.id)
	_check(bool(controller.modify_selected_sphere_security({"security_tier": 3, "access_difficulty_modifier": 2, "path_unlock_difficulty_modifier": 4, "system_trace_pressure": 1, "enabled": true}).success) and int(graph.get_security_sleeve(authored_sleeve_id).metadata.access_difficulty_modifier) == 2, "sphere security edits are available from a member node")
	controller.select_object(NetworkSelectionState.Kind.SPHERE, authored_sphere_id)
	var delete_sphere_result := controller.delete_selected_sphere()
	var delete_sphere_command := controller.command_history.back() as NetworkAuthorCommand
	_check(bool(delete_sphere_result.success) and graph.get_node(start.id) != null and graph.get_sphere(authored_sphere_id) == null, "deleting sphere preserves member nodes")
	_check(bool(delete_sphere_command.undo().success) and graph.get_sphere(authored_sphere_id) != null and graph.get_node(start.id).sphere_id == authored_sphere_id, "delete-sphere command restores membership on undo")
	var captured := controller.capture_document()
	_check(captured.format_version == NetworkDocument.CURRENT_FORMAT_VERSION and captured.validate().is_empty(), "runtime graph captures as a valid versioned document")
	var plaintext := NetworkDocumentSerializer.serialize(captured)
	_check(plaintext == NetworkDocumentSerializer.serialize(captured), "network serialization is deterministic")
	var encoded := NetworkPackageCodec.encode(plaintext)
	var decoded := NetworkPackageCodec.decode(encoded.data)
	_check(bool(encoded.success) and bool(decoded.success) and decoded.data == plaintext, "authenticated package codec round trips")
	_check(not encoded.data.get_string_from_utf8().contains(String(captured.network_id)), "encrypted package does not expose serialized network text")
	var corrupted: PackedByteArray = encoded.data.duplicate(); corrupted[corrupted.size() - 1] ^= 1
	_check(not bool(NetworkPackageCodec.decode(corrupted).success), "corrupted package is rejected")
	var unsupported: PackedByteArray = encoded.data.duplicate(); unsupported[8] = 0; unsupported[9] = 99
	_check(not bool(NetworkPackageCodec.decode(unsupported).success), "unsupported package version is rejected")
	var invalid := NetworkDocument.from_dict(captured.to_dict()); invalid.paths.append({"id": &"BROKEN_PATH", "node_a": &"MISSING", "node_b": start.id})
	_check(invalid.validate().any(func(issue): return issue.code == "DANGLING_PATH"), "validation reports dangling path endpoints")
	var save_path := "res://.test_network_authoring_round_trip.netspace"
	var save_result := controller.save_current_network(save_path)
	var saved_file := FileAccess.open(save_path, FileAccess.READ); var saved_bytes := saved_file.get_buffer(saved_file.get_length()); saved_file.close()
	_check(saved_bytes.slice(0, NetworkPackageCodec.MAGIC.length()).get_string_from_ascii() == NetworkPackageCodec.MAGIC and not saved_bytes.get_string_from_utf8().contains(String(captured.network_id)), "authoring save writes encrypted .netspace package")
	_check(bool(NetworkDocumentSerializer.save_plaintext_debug(captured, "res://.test_network_authoring_diagnostic.netspace.json").success), "debug plaintext diagnostic export remains available")
	var graph_identity_after_save := Game.network_graph.get_instance_id()
	var load_result := controller.load_network(save_path)
	_check(bool(save_result.success) and bool(load_result.success), ".netspace saves and loads through authoring")
	_check(Game.network_graph.get_instance_id() == graph_identity_after_save and Game.network_graph.get_node(start.id) != null, "load preserves live graph identity and restores playable nodes")
	controller.set_mode(NetworkAuthoringState.Mode.PLAYER)
	_check(not Game._debug_author_god_mode, "leaving authoring clears gameplay bypass")
	controller.queue_free()
	if failures.is_empty(): print("NETWORK_AUTHORING_TESTS: PASS")
	else:
		for failure in failures: push_error("NETWORK_AUTHORING_TESTS: %s" % failure)
	get_tree().quit(failures.size())

func _check(condition: bool, message: String) -> void:
	if not condition: failures.append(message)
