extends SceneTree

var failures := 0
var assertions := 0

func _init() -> void:
	var graph := NetworkGraph.new()
	var sphere_a := SphereDefinition.new(&"SPHERE_A", "Operations", [], &"SLEEVE_A")
	var sphere_b := SphereDefinition.new(&"SPHERE_B", "External", [], &"SLEEVE_B")
	var sphere_c := SphereDefinition.new(&"SPHERE_C", "Black Archive", [], &"SLEEVE_C")
	graph.add_sphere(sphere_a); graph.add_sphere(sphere_b); graph.add_sphere(sphere_c)
	for data in [[&"A1", sphere_a.id], [&"A2", sphere_a.id], [&"A3", sphere_a.id], [&"A4", sphere_a.id], [&"B1", sphere_b.id], [&"C1", sphere_c.id]]:
		graph.add_node(NetworkNodeDefinition.new(data[0], String(data[0]), NetworkNodeDefinition.NodeType.SYSTEM, 2, true, &"CORP", data[1]))
	graph.add_link(NetworkLinkDefinition.new(&"A1_A2", &"A1", &"A2"))
	graph.add_link(NetworkLinkDefinition.new(&"A2_A3", &"A2", &"A3"))
	graph.add_link(NetworkLinkDefinition.new(&"A3_A4", &"A3", &"A4"))
	graph.add_link(NetworkLinkDefinition.new(&"A2_B1", &"A2", &"B1"))
	graph.add_link(NetworkLinkDefinition.new(&"A2_C1", &"A2", &"C1"))
	graph.add_security_sleeve(SecuritySleeve.new(&"SLEEVE_A", "Operations Sleeve", [&"A1", &"A2"]))
	graph.add_security_sleeve(SecuritySleeve.new(&"SLEEVE_B", "External Sleeve", [&"B1"]))
	var knowledge := PlayerKnowledge.new()
	for node_id in [&"A1", &"A2", &"A3", &"B1"]: knowledge.reveal_node(graph.get_node(node_id), KnowledgeLevel.Value.IDENTIFIED)
	knowledge.reveal_link(graph.get_link(&"A1_A2"), KnowledgeLevel.Value.IDENTIFIED)
	knowledge.reveal_link(graph.get_link(&"A2_B1"), KnowledgeLevel.Value.IDENTIFIED)
	knowledge.reveal_link(graph.get_link(&"A2_C1"), KnowledgeLevel.Value.IDENTIFIED)
	knowledge.reveal_sphere_identity(sphere_b, &"ROUTING_INTELLIGENCE")
	knowledge.set_local_system_access_node(&"A1", &"LOCAL_SAN", true)
	knowledge.reveal_node_capability(&"A2", NodeCapabilityType.Value.OBJECTIVE, &"MISSION")
	knowledge.reveal_node_capability(&"A3", NodeCapabilityType.Value.ICE, &"ICE_OBSERVATION", &"ICE_1")
	knowledge.reveal_security_sleeve(graph.get_security_sleeve(&"SLEEVE_A"), graph)
	var position := PlayerNetworkPosition.new(&"A1", 10)
	var tracker := CurrentSphereTracker.new(graph); tracker.register_player(&"PLAYER", position)
	var canvas := SphereMinimapCanvas.new()
	canvas.size = Vector2(340, 178)
	canvas.set_models(graph, position, knowledge, tracker)
	var visible := canvas.visible_node_ids()
	_expect(visible.size() == 3 and visible.has(&"A1") and visible.has(&"A2") and visible.has(&"A3"), "minimap includes every known node in the current Sphere")
	_expect(not visible.has(&"B1"), "minimap excludes known nodes in unrelated Spheres")
	_expect(not visible.has(&"A4") and not canvas.canonical_positions.has(&"A4"), "authoritative hidden Sphere member creates no node or layout gap")
	_expect(canvas.known_internal_links().size() == 1 and canvas.known_internal_links()[0].id == &"A1_A2", "only known internal connections are drawn")
	_expect(canvas.known_exit_links().size() == 2, "multiple known cross-Sphere connections are represented as exits")
	var exit_markers := canvas.external_connection_markers()
	_expect(exit_markers.size() == 2 and exit_markers[0].inside_node_id == &"A2" and exit_markers[1].inside_node_id == &"A2", "multiple external links receive independent boundary markers at their shared host")
	_expect(exit_markers.any(func(marker): return marker.destination_known and marker.destination_label == "EXTERNAL") and exit_markers.any(func(marker): return not marker.destination_known and marker.destination_label == "UNKNOWN NETWORK REGION"), "external marker labels reveal only discovered destination Sphere identity")
	_expect(exit_markers[0].host_exit_index != exit_markers[1].host_exit_index and not visible.has(&"B1") and not visible.has(&"C1"), "external markers fan deterministically without drawing either destination Sphere")
	_expect(not canvas.known_internal_links().any(func(link): return link.id == &"A2_A3"), "undiscovered connections remain hidden")
	_expect(knowledge.get_node_view(&"A1").local_san_present and knowledge.get_node_view(&"A2").capability_types.has(NodeCapabilityType.Value.OBJECTIVE) and knowledge.get_node_view(&"A3").capability_types.has(NodeCapabilityType.Value.ICE), "SAN, objective, and known ICE markers come from PlayerKnowledge")
	_expect(knowledge.knows_security_sleeve(&"SLEEVE_A") and knowledge.get_known_security_sleeves()[0].current_members.size() == 2, "current Security Sleeve relationships require explicit knowledge")
	var layout_before := canvas.canonical_positions.duplicate(true)
	knowledge.reveal_node_level(graph.get_node(&"A2"))
	var layout_after := canvas.canonical_positions.duplicate(true)
	_expect(layout_before == layout_after, "player-map positions remain stable when knowledge detail changes without topology discovery")
	var topology_result := knowledge.reveal_sphere_topology(graph, sphere_a.id, &"ROUTING_TABLE")
	canvas.refresh()
	var revealed_view := knowledge.get_node_view(&"A4")
	_expect(topology_result.nodes_revealed == 1 and canvas.visible_node_ids().has(&"A4"), "whole-Sphere topology intelligence reveals previously unknown node existence")
	_expect(not bool(revealed_view.level_known) and not bool(revealed_view.contents_known) and revealed_view.capability_types.is_empty(), "topology intelligence does not reveal security level or contents")
	_expect(canvas.known_internal_links().size() == 3, "whole-Sphere topology intelligence reveals internal connections without hidden detail")
	position.relocate(&"B1")
	_expect(canvas.current_sphere_id == sphere_b.id and canvas.visible_node_ids() == [&"B1"], "minimap switches cleanly when the player crosses Spheres")
	var scene := load("res://cyberspace/display/minimap/SphereMinimap.tscn") as PackedScene
	var panel := scene.instantiate()
	_expect(panel.find_child("ToggleButton", true, false) != null and panel.find_child("Canvas", true, false) != null, "production minimap is collapsible and retains a dedicated read-only canvas")
	panel.free(); canvas.free()
	_test_simplified_node_renderer()
	_test_player_and_san_indicators()
	_test_compact_identity_header()
	_test_lightweight_interaction()
	_test_historical_sleeve_split()
	print("%s: %d Sphere minimap assertions" % ["PASS" if failures == 0 else "FAIL", assertions])
	quit(failures)

func _test_simplified_node_renderer() -> void:
	var renderer := SphereMinimapNode.new()
	var noisy_capabilities: Array[int] = [NodeCapabilityType.Value.FEED, NodeCapabilityType.Value.DATASTORE, NodeCapabilityType.Value.DATABASE, NodeCapabilityType.Value.SOFTWARE, NodeCapabilityType.Value.SYSTEM_ACCESS_NODE, NodeCapabilityType.Value.OBJECTIVE, NodeCapabilityType.Value.ICE]
	renderer.configure(&"TACTICAL", {"id": &"TACTICAL", "display_name": "Tactical", "level_known": false, "capability_types": noisy_capabilities, "local_san_present": true, "critical_alert": true}, true, true)
	_expect(renderer.hex_radius() < renderer.visualization_config.radius(false) * 0.2, "dedicated minimap hex is much smaller than a main graph hex")
	_expect(renderer.resolved_level_style() == renderer.visualization_config.unknown_level_style, "minimap UNKNOWN uses the shared grey node-level resource")
	_expect(renderer.display_label() == "???", "discovered existence does not leak an unidentified node label")
	var markers := renderer.semantic_markers()
	_expect(markers.has(&"CURRENT") and markers.has(&"SAN") and markers.has(&"OBJECTIVE") and markers.has(&"ICE") and markers.has(&"SPHERE_EXIT") and markers.has(&"CRITICAL_ALERT"), "renderer supports only the six high-priority tactical markers")
	_expect(not markers.has(&"FEED") and not markers.has(&"DATASTORE") and not markers.has(&"DATABASE") and not markers.has(&"SOFTWARE"), "low-priority node contents never enter the minimap marker set")
	renderer.configure(&"KNOWN", {"id": &"KNOWN", "display_name": "Known", "level_known": true, "security_level": 4, "capability_types": []}, false, false)
	_expect(renderer.resolved_level_style() == renderer.visualization_config.style_for_level(4, true), "known minimap level reuses the main graph security appearance")
	renderer.free()

func _test_player_and_san_indicators() -> void:
	var graph := NetworkGraph.new()
	var sphere := SphereDefinition.new(&"SPHERE_LOCAL", "Local subnet")
	graph.add_sphere(sphere)
	graph.add_node(NetworkNodeDefinition.new(&"NODE_A", "Node A", NetworkNodeDefinition.NodeType.SYSTEM, 2, true, &"CORP", sphere.id))
	graph.add_node(NetworkNodeDefinition.new(&"NODE_F", "Node F", NetworkNodeDefinition.NodeType.SYSTEM, 4, true, &"CORP", sphere.id))
	graph.add_link(NetworkLinkDefinition.new(&"A_F", &"NODE_A", &"NODE_F"))
	var knowledge := PlayerKnowledge.new()
	knowledge.reveal_node(graph.get_node(&"NODE_A"), KnowledgeLevel.Value.IDENTIFIED)
	knowledge.reveal_node(graph.get_node(&"NODE_F"), KnowledgeLevel.Value.IDENTIFIED)
	knowledge.reveal_link(graph.get_link(&"A_F"), KnowledgeLevel.Value.IDENTIFIED)
	var position := PlayerNetworkPosition.new(&"NODE_F")
	var san_controller := SystemAccessNodeController.new(graph, knowledge, &"PLAYER")
	var san := san_controller.create_san(&"PLAYER", &"RUN_LOCAL", &"DECK", &"NODE_A")
	var canvas := SphereMinimapCanvas.new()
	canvas.size = Vector2(340, 178)
	canvas.set_models(graph, position, knowledge)
	var node_a := canvas.minimap_node_for(&"NODE_A")
	var node_f := canvas.minimap_node_for(&"NODE_F")
	_expect(san != null and node_a.has_san and not node_a.is_current, "SAN and player may be shown on different minimap nodes")
	_expect(node_f.is_current and not node_f.has_san, "the player's current node owns the distinct inner player treatment")
	var original_a_sphere := graph.get_node(&"NODE_A").sphere_id
	var original_f_sphere := graph.get_node(&"NODE_F").sphere_id
	_expect(san_controller.relocate_san(&"RUN_LOCAL", &"NODE_F").success, "the production SAN relocation path used by Doorstop succeeds")
	node_a = canvas.minimap_node_for(&"NODE_A")
	node_f = canvas.minimap_node_for(&"NODE_F")
	_expect(not node_a.has_san and node_f.has_san and node_f.is_current, "SAN relocation immediately moves the indicator and composes it with the player marker")
	_expect(node_f.semantic_markers().has(&"CURRENT") and node_f.semantic_markers().has(&"SAN"), "co-located player and SAN retain both semantic indicators")
	_expect(node_f.marker_anchor(&"CURRENT") != node_f.marker_anchor(&"SAN"), "co-located player and SAN use separate visual anchors")
	_expect(graph.get_node(&"NODE_A").sphere_id == original_a_sphere and graph.get_node(&"NODE_F").sphere_id == original_f_sphere, "SAN relocation never mutates Sphere membership")
	canvas.free()

func _test_compact_identity_header() -> void:
	var graph := NetworkGraph.new()
	var sphere := SphereDefinition.new(&"LOCAL_04", "Finance")
	graph.add_sphere(sphere)
	for node_id in [&"LEDGER", &"PAYROLL", &"HIDDEN"]:
		graph.add_node(NetworkNodeDefinition.new(node_id, String(node_id), NetworkNodeDefinition.NodeType.SYSTEM, 2, true, &"CORP", sphere.id))
	var knowledge := PlayerKnowledge.new()
	knowledge.discover_node(graph.get_node(&"LEDGER"))
	knowledge.discover_node(graph.get_node(&"PAYROLL"))
	var position := PlayerNetworkPosition.new(&"LEDGER")
	var panel := SphereMinimap.new()
	panel.canvas = SphereMinimapCanvas.new()
	panel.canvas.size = Vector2(340, 178)
	panel.add_child(panel.canvas)
	panel.title_label = Label.new()
	panel.identity_label = Label.new()
	panel.meta_label = Label.new()
	panel.add_child(panel.title_label)
	panel.add_child(panel.identity_label)
	panel.add_child(panel.meta_label)
	panel.set_models(graph, position, knowledge)
	var unknown_view := panel.get_identity_header_view()
	_expect(not unknown_view.identity_known and unknown_view.known_nodes == 2 and not unknown_view.total_known, "header counts known nodes without leaking authoritative hidden topology")
	_expect(panel.title_label.text == "SPHERE // UNKNOWN" and panel.meta_label.text == "KNOWN NODES: 2", "unknown identity and size use the compact knowledge-only presentation")
	knowledge.reveal_sphere_identity(sphere, &"CORPORATE_DIRECTORY")
	knowledge.set_sphere_security_state(sphere.id, &"ELEVATED", &"SECURITY_MONITOR")
	_expect(panel.title_label.text == "SPHERE // LOCAL_04" and panel.identity_label.text == "FINANCE" and "SECURITY: ELEVATED" in panel.meta_label.text, "known Sphere identity and security state update the header")
	knowledge.reveal_sphere_node_total(sphere.id, 3)
	_expect("KNOWN NODES: 2 / 3" in panel.meta_label.text, "known total size is displayed only after explicit topology intelligence")
	panel.free()

func _test_lightweight_interaction() -> void:
	var graph := NetworkGraph.new()
	var sphere := SphereDefinition.new(&"INTERACTION", "Interaction")
	graph.add_sphere(sphere)
	graph.add_node(NetworkNodeDefinition.new(&"KNOWN", "Known Relay", NetworkNodeDefinition.NodeType.ROUTER, 1, true, &"CORP", sphere.id))
	graph.add_node(NetworkNodeDefinition.new(&"MYSTERY", "Secret Name", NetworkNodeDefinition.NodeType.SYSTEM, 4, true, &"CORP", sphere.id))
	var knowledge := PlayerKnowledge.new()
	knowledge.reveal_node(graph.get_node(&"KNOWN"), KnowledgeLevel.Value.IDENTIFIED)
	knowledge.discover_node(graph.get_node(&"MYSTERY"))
	var position := PlayerNetworkPosition.new(&"KNOWN")
	var canvas := SphereMinimapCanvas.new(); canvas.size = Vector2(340, 178); canvas.set_models(graph, position, knowledge)
	var focus_requests: Array[StringName] = []
	canvas.node_focus_requested.connect(func(node_id: StringName): focus_requests.append(node_id))
	var original_node := position.current_node_id
	_expect(canvas.request_focus_node(&"MYSTERY") and focus_requests == [&"MYSTERY"] and position.current_node_id == original_node, "selecting a minimap node emits focus without performing movement")
	_expect(not canvas.request_focus_node(&"NOT_KNOWN") and focus_requests.size() == 1, "minimap rejects focus requests for nodes outside the player map")
	_expect(canvas.focus_current_player() and focus_requests.back() == &"KNOWN", "optional center control resolves to the current player node")
	var known_visual := canvas.minimap_node_for(&"KNOWN")
	var mystery_visual := canvas.minimap_node_for(&"MYSTERY")
	_expect(known_visual.known_name_for_inspection() == "KNOWN RELAY", "hover and keyboard focus expose a known node name")
	_expect(mystery_visual.known_name_for_inspection() == "UNKNOWN NODE" and not mystery_visual.known_name_for_inspection().contains("SECRET"), "minimap inspection never leaks an undiscovered node identity")
	canvas.free()

func _test_historical_sleeve_split() -> void:
	var graph := NetworkGraph.new()
	var sphere := SphereDefinition.new(&"SPHERE_A", "Sphere A", [], &"SLEEVE_A")
	graph.add_sphere(sphere)
	for index in range(1, 5):
		var node_id := StringName("NODE_%d" % index)
		graph.add_node(NetworkNodeDefinition.new(node_id, "Node %d" % index, NetworkNodeDefinition.NodeType.SYSTEM, index, true, &"CORP", sphere.id))
	var original := SecuritySleeve.new(&"SLEEVE_A", "Sleeve A", [&"NODE_1", &"NODE_2", &"NODE_3", &"NODE_4"])
	graph.add_security_sleeve(original)
	var knowledge := PlayerKnowledge.new()
	for index in range(1, 5): knowledge.reveal_node(graph.get_node(StringName("NODE_%d" % index)), KnowledgeLevel.Value.IDENTIFIED)
	var position := PlayerNetworkPosition.new(&"NODE_1")
	var canvas := SphereMinimapCanvas.new(); canvas.size = Vector2(340, 178); canvas.set_models(graph, position, knowledge)
	_expect(graph.split_security_sleeve(&"SLEEVE_A", {&"SLEEVE_A1": [&"NODE_1", &"NODE_2"], &"SLEEVE_A2": [&"NODE_3"]}), "an active Security Sleeve can split into current sub-sleeves")
	knowledge.reveal_security_sleeve(graph.get_security_sleeve(&"SLEEVE_A1"), graph)
	knowledge.reveal_security_sleeve(graph.get_security_sleeve(&"SLEEVE_A2"), graph)
	canvas.refresh()
	var visible := canvas.visible_node_ids()
	_expect(visible.size() == 4 and sphere.node_ids.size() == 4, "all four historically related nodes remain visible in the Sphere minimap after sleeve split")
	_expect(graph.get_node(&"NODE_1").sphere_id == sphere.id and graph.get_node(&"NODE_2").sphere_id == sphere.id and graph.get_node(&"NODE_3").sphere_id == sphere.id and graph.get_node(&"NODE_4").sphere_id == sphere.id, "sleeve segmentation never mutates node sphere_id")
	var groups := canvas.known_current_sleeve_groups()
	_expect(groups[&"SLEEVE_A1"].size() == 2 and groups[&"SLEEVE_A2"] == [&"NODE_3"], "minimap exposes current sleeve groups separately from Sphere membership")
	var overlays := canvas.security_sleeve_overlay_records()
	_expect(overlays.size() == 2 and overlays.any(func(record): return record.sleeve_id == &"SLEEVE_A1" and record.node_ids.size() == 2), "optional overlay follows the two current post-split Sleeve groupings")
	var stable_layout := canvas.canonical_positions.duplicate(true)
	canvas.set_security_sleeves_visible(false)
	_expect(canvas.security_sleeve_overlay_records().is_empty() and canvas.visible_node_ids().size() == 4 and canvas.canonical_positions == stable_layout, "disabling Sleeve decoration leaves stable Sphere contents and layout untouched")
	canvas.set_security_sleeves_visible(true)
	_expect(graph.get_current_sleeve_ids_for_node(&"NODE_4").is_empty() and visible.has(&"NODE_4"), "a node outside active sleeve protection remains part of its Sphere")
	_expect(sphere.original_security_sleeve_id == &"SLEEVE_A" and graph.get_security_sleeve(&"SLEEVE_A").state == SecuritySleeve.State.SPLIT, "original sleeve provenance remains addressable after the split")
	var other := SphereDefinition.new(&"SPHERE_B", "Sphere B"); graph.add_sphere(other)
	_expect(graph.move_node_to_sphere(&"NODE_4", other.id) and graph.get_node(&"NODE_4").sphere_id == other.id, "only the explicit network reconfiguration API moves a node to another Sphere")
	canvas.free()

func _expect(condition: bool, description: String) -> void:
	assertions += 1
	if not condition:
		failures += 1
		printerr("FAILED: %s" % description)
