class_name NodeServiceCatalog
extends RefCounted

const AUTHENTICATION := &"AUTHENTICATION"
const SERVICE_PROCESS_CONTROL := &"SERVICE_PROCESS_CONTROL"
const ROUTE_CONTROL := &"ROUTE_CONTROL"
const FILESYSTEM := &"FILESYSTEM"
const DATABASE := &"DATABASE"
const ENCRYPTED_DATA := &"ENCRYPTED_DATA"
const MESSAGING := &"MESSAGING"
const VOICE_COMMS := &"VOICE_COMMS"
const VIDEO_FEED := &"VIDEO_FEED"
const PHYSICAL_CONTROL := &"PHYSICAL_CONTROL"
const PHYSICAL_SENSORS := &"PHYSICAL_SENSORS"
const ALARM := &"ALARM"
const LOGGING := &"LOGGING"
const ICE_CONTROL := &"ICE_CONTROL"
const SECURITY_SLEEVE_INTERFACE := &"SECURITY_SLEEVE_INTERFACE"
const SESSION_SAN_CONTROL := &"SESSION_SAN_CONTROL"
const MALWARE := &"MALWARE"
const INDEX_SEARCH := &"INDEX_SEARCH"
const SYSTEM_ADMINISTRATION := &"SYSTEM_ADMINISTRATION"

const ALL: Array[StringName] = [AUTHENTICATION, SERVICE_PROCESS_CONTROL, ROUTE_CONTROL, FILESYSTEM, DATABASE, ENCRYPTED_DATA, MESSAGING, VOICE_COMMS, VIDEO_FEED, PHYSICAL_CONTROL, PHYSICAL_SENSORS, ALARM, LOGGING, ICE_CONTROL, SECURITY_SLEEVE_INTERFACE, SESSION_SAN_CONTROL, MALWARE, INDEX_SEARCH, SYSTEM_ADMINISTRATION]

const DEFAULT_OPERATIONS := {
	AUTHENTICATION: [&"SCAN", &"ENUMERATE", &"BYPASS", &"AUTHENTICATE", &"SPOOF"],
	SERVICE_PROCESS_CONTROL: [&"SCAN", &"ENUMERATE", &"MONITOR", &"ACTIVATE", &"DEACTIVATE", &"INJECT", &"REDIRECT", &"DISABLE"],
	ROUTE_CONTROL: [&"SCAN", &"ENUMERATE", &"MONITOR", &"REDIRECT", &"ACTIVATE", &"DEACTIVATE"],
	FILESYSTEM: [&"SCAN", &"ENUMERATE", &"READ", &"SEARCH", &"DOWNLOAD", &"UPLOAD", &"EDIT", &"DELETE"],
	DATABASE: [&"SCAN", &"ENUMERATE", &"READ", &"SEARCH", &"DOWNLOAD", &"UPLOAD", &"EDIT", &"DELETE", &"INJECT"],
	ENCRYPTED_DATA: [&"SCAN", &"READ", &"DOWNLOAD", &"UPLOAD", &"EDIT", &"ENCRYPT", &"DECRYPT"],
	MESSAGING: [&"SCAN", &"READ", &"MONITOR", &"INTERCEPT", &"INJECT", &"DELETE"],
	VOICE_COMMS: [&"SCAN", &"MONITOR", &"INTERCEPT", &"INJECT", &"REDIRECT", &"SUPPRESS"],
	VIDEO_FEED: [&"SCAN", &"MONITOR", &"INTERCEPT", &"INJECT", &"REDIRECT", &"SUPPRESS", &"DISABLE"],
	PHYSICAL_CONTROL: [&"SCAN", &"MONITOR", &"ACTIVATE", &"DEACTIVATE", &"UNLOCK", &"LOCK", &"DISABLE"],
	PHYSICAL_SENSORS: [&"SCAN", &"MONITOR", &"INJECT", &"SUPPRESS", &"DISABLE"],
	ALARM: [&"SCAN", &"MONITOR", &"ACTIVATE", &"DEACTIVATE", &"SUPPRESS", &"DISABLE"],
	LOGGING: [&"SCAN", &"READ", &"SEARCH", &"EDIT", &"DELETE", &"SCRUB", &"FORGE"],
	ICE_CONTROL: [&"SCAN", &"ENUMERATE", &"MONITOR", &"ACTIVATE", &"DEACTIVATE", &"REDIRECT", &"DISABLE"],
	SECURITY_SLEEVE_INTERFACE: [&"SCAN", &"MONITOR", &"REQUEST", &"EDIT", &"ACTIVATE", &"DEACTIVATE"],
	SESSION_SAN_CONTROL: [&"SCAN", &"ENUMERATE", &"MONITOR", &"AUTHENTICATE", &"REDIRECT", &"ACTIVATE", &"DEACTIVATE"],
	MALWARE: [&"SCAN", &"ENUMERATE", &"MONITOR", &"INJECT", &"ACTIVATE", &"DEACTIVATE", &"DELETE", &"DISABLE"],
	INDEX_SEARCH: [&"SCAN", &"ENUMERATE", &"SEARCH", &"READ"],
	SYSTEM_ADMINISTRATION: [&"SCAN", &"ENUMERATE", &"AUTHENTICATE", &"MONITOR", &"RUN_PROGRAM", &"INSTALL_UTILITY", &"UNLOAD_UTILITY", &"ACTIVATE", &"DEACTIVATE"],
}

static func normalize(value: Variant) -> StringName:
	return StringName(String(value).strip_edges().to_upper().replace("/", "_").replace(" ", "_"))

static func is_supported(value: Variant) -> bool:
	return ALL.has(normalize(value))

static func default_operations(service_type: StringName) -> Array[StringName]:
	var result: Array[StringName] = []
	result.assign(DEFAULT_OPERATIONS.get(normalize(service_type), []))
	return result
